version: '3.8'

services:
  # 1. La Base de Données (MongoDB Local)
  mongo:
    image: mongo:latest
    container_name: todo-mongo
    ports:
      - "27017:27017" # Port standard Mongo
    volumes:
      - mongo-data:/data/db # Persistance des données sur ton disque
    networks:
      - app-network

  # 2. Le Backend Java
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    environment:
      # C'est ici qu'on fait le lien !
      # On dit à Spring : "Connecte-toi au conteneur qui s'appelle 'mongo'"
      - MONGO_URI=mongodb://mongo:27017/tododb
    depends_on:
      - mongo
    networks:
      - app-network

  # 3. Le Frontend React
  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - app-network

volumes:
  mongo-data:

networks:
  app-network:
    driver: bridge