name: Spring Boot CI

# Se déclenche quand on push sur la branche 'main'
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    # 1. GitHub récupère ton code
    - name: Checkout code
      uses: actions/checkout@v4

    # 2. On installe Java 17 (La version que tu as choisie)
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven # Optimisation : garde les bibliothèques en mémoire pour aller plus vite

    # 3. Le cœur du réacteur : Compile + Test
    # On donne les droits d'exécution au script maven au cas où
    - name: Grant execute permission for gradlew
      run: chmod +x mvnw

    - name: Build with Maven
      run: ./mvnw clean verify