name: Spring Boot CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    # --- LA MAGIE EST ICI ---
    # On définit le dossier de travail par défaut pour toutes les commandes 'run'
    defaults:
      run:
        working-directory: ./todo/backend

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
        # Il faut préciser au cache où trouver le pom.xml car il n'est pas à la racine
        cache-dependency-path: todo/backend/pom.xml

    - name: Grant execute permission for mvnw
      # Grâce au 'defaults' plus haut, on est déjà dans le bon dossier !
      run: chmod +x mvnw

    - name: Build with Maven
      # Idem, on lance la commande directement
      run: ./mvnw clean verify